---
- name: '[dependencies] Install ohmyzsh dependencies for non-Darwin systems: zsh, git'
  package:
    name: [ 'zsh', 'git', 'bc' ]
    state: present
  become: yes  # disable this for MacOS
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when: "'Darwin' not in ansible_os_family"
  tags:
  - ohmyzsh
  - ohmyzsh_dependencies

- name: '[dependencies] Make sure locales package is installed on Debian'
  apt: name=locales state=present
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when: "'Darwin' not in ansible_os_family"
  tags:
  - ohmyzsh
  - ohmyzsh_dependencies

# MacOS:
- name: '[dependencies] Install powerlevel9k dependencies: bc'
  homebrew: name=bc state=present
  become: no  # always the case with homebrew
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when:
  - ohmyzsh_powerlevel9k
  - "'Darwin' in ansible_os_family"
  tags:
  - ohmyzsh
  - ohmyzsh_dependencies

- name: '[dependencies] Install zsh for MacOS; install_options: --with-unicode9, --without-etcdir'
  homebrew:
    install_options:
    - 'with-unicode9'
    - 'without-etcdir'
    name: zsh
    state: present
    update_homebrew: yes
  become: no
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when: "'Darwin' in ansible_os_family"
  tags:
  - ohmyzsh
  - ohmyzsh_dependencies
...
